name: "godot-ci export"
on: workflow_dispatch

env:
  GODOT_VERSION: 4.0.1
  EXPORT_NAME: multiplayer_pong
  PROJECT_PATH: multiplayer_pong
  
jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: seanmaxwell/godot-ci:mono-4.0.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          apt-get update -qq
          apt-get install -y apt-transport-https
          apt-get update -qq
          apt-get install -y dotnet-sdk-6.0
          cd $PROJECT_PATH
          godot -v --headless --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: build/linux
